import { describe, expect, it } from "vitest";
import { formatPairingCode, isPairingCodeComplete, PAIRING_ALPHABET, PAIRING_CODE_CHARS } from "../src/lib/pairing-code";

// A whole code in the alphabet the sidecar generates from: no I, O, 0 or 1.
const CODE = "ABCDEFGHJKLM";
const SHOWN = "ABCD-EFGH-JKLM";

describe("pairing code field", () => {
  it("calls a code complete on its characters, not on its dashes", () => {
    expect(isPairingCodeComplete("")).toBe(false);
    expect(isPairingCodeComplete("ABCDEFGHJK")).toBe(false);
    expect(isPairingCodeComplete(CODE)).toBe(true);
    expect(isPairingCodeComplete("abcd efgh jklm")).toBe(true);
    expect(isPairingCodeComplete(SHOWN)).toBe(true);
    // A character the alphabet drops is not one of the twelve, so eleven
    // characters plus one it cannot hold is not a whole code.
    expect(isPairingCodeComplete(`${CODE.slice(0, 11)}I`)).toBe(false);
  });

  it("keeps the alphabet and the length the sidecar generates against", () => {
    // Twelve characters, four-plus-four-plus-four, from an alphabet with the
    // look-alikes removed: the field's shape and the sidecar's decoder have to
    // agree, or a code generated by one cannot be typed into the other.
    expect(PAIRING_CODE_CHARS).toBe(12);
    expect(formatPairingCode("A".repeat(20))).toBe("AAAA-AAAA-AAAA");
    expect(PAIRING_ALPHABET).not.toMatch(/[IO01]/);
    for (const character of PAIRING_ALPHABET) {
      expect(formatPairingCode(`AAA${character}`), character).toBe(`AAA${character}`);
    }
  });
});
