import { describe, expect, it } from "vitest";
import { formatPairingCode, isPairingCodeComplete, PAIRING_ALPHABET, PAIRING_CODE_CHARS } from "../src/lib/pairing-code";

// A whole code in the alphabet the sidecar generates from: no I, O, 0 or 1.
const CODE = "ABCDEFGHJKLM";
const SHOWN = "ABCD-EFGH-JKLM";

describe("pairing code field", () => {
  it("groups what the reader has typed in fours, dashes and all", () => {
    expect(formatPairingCode("")).toBe("");
    expect(formatPairingCode("A")).toBe("A");
    expect(formatPairingCode("ABCD")).toBe("ABCD");
    // The dash appears as the fifth character arrives, not at the end: the
    // reader sees the shape they were shown fill in.
    expect(formatPairingCode("ABCDE")).toBe("ABCD-E");
    expect(formatPairingCode("ABCDEFGH")).toBe("ABCD-EFGH");
    expect(formatPairingCode(CODE)).toBe(SHOWN);
  });

  it("takes a paste in any shape of the code the reader was shown", () => {
    // Lower case, spaces, dashes, a trailing newline from a copied line, and
    // more than one code's worth of characters all arrive at one string.
    for (const pasted of [
      "abcdefghjklm", "abcd efgh jklm", "ABCD EFGH JKLM", "abcd-efgh-jklm",
      `  ${SHOWN}\n`, `${SHOWN}-9999`,
    ]) {
      expect(formatPairingCode(pasted), pasted).toBe(SHOWN);
    }
  });

  it("drops what a code cannot hold, and never grows past one", () => {
    // The alphabet has the look-alikes taken out of it — no I, O, 0 or 1 — so a
    // character outside it is not part of any code and is not shown as if it
    // were.
    expect(formatPairingCode("AIB0O1")).toBe("AB");
    expect(formatPairingCode("ab/cd.ef gh-jk lm")).toBe(SHOWN);
    expect(formatPairingCode(`${CODE}NOPQ`)).toBe(SHOWN);
    expect(formatPairingCode(null)).toBe("");
    expect(formatPairingCode(undefined)).toBe("");
    expect(formatPairingCode(42)).toBe("42");
  });

  it("calls a code complete on its characters, not on its dashes", () => {
    expect(isPairingCodeComplete("")).toBe(false);
    expect(isPairingCodeComplete("ABCDEFGHJK")).toBe(false);
    expect(isPairingCodeComplete(CODE)).toBe(true);
    expect(isPairingCodeComplete("abcd efgh jklm")).toBe(true);
    expect(isPairingCodeComplete(SHOWN)).toBe(true);
    // A character the alphabet drops is not one of the twelve, so eleven
    // characters plus one it cannot hold is not a whole code.
    expect(isPairingCodeComplete(`${CODE.slice(0, 11)}I`)).toBe(false);
  });

  it("keeps the alphabet and the length the sidecar generates against", () => {
    // Twelve characters, four-plus-four-plus-four, from an alphabet with the
    // look-alikes removed: the field's shape and the sidecar's decoder have to
    // agree, or a code generated by one cannot be typed into the other.
    expect(PAIRING_CODE_CHARS).toBe(12);
    expect(formatPairingCode("A".repeat(20))).toBe("AAAA-AAAA-AAAA");
    expect(PAIRING_ALPHABET).not.toMatch(/[IO01]/);
    for (const character of PAIRING_ALPHABET) {
      expect(formatPairingCode(`AAA${character}`), character).toBe(`AAA${character}`);
    }
  });
});
